# Clock signal
set_property PACKAGE_PIN W5 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
create_clock -period 10.000 -name sys_clk_pin -waveform {0.000 5.000} -add [get_ports clk]

# LEDs
set_property PACKAGE_PIN U16 [get_ports {led}]
set_property IOSTANDARD LVCMOS33 [get_ports {led}]
set_property DRIVE 12 [get_ports {led}]     
set_property SLEW FAST [get_ports {led}] 
set_property PULLDOWN TRUE [get_ports {led}]

# set_property PACKAGE_PIN U16 [get_ports {led}]
# set_property IOSTANDARD LVCMOS33 [get_ports {led}]
# set_property PACKAGE_PIN E19 [get_ports {led[1]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {led[1]}]
# set_property PACKAGE_PIN U19 [get_ports {led[2]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {led[2]}]
# set_property PACKAGE_PIN V19 [get_ports {led[3]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {led[3]}]
# set_property PACKAGE_PIN W18 [get_ports {led[4]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {led[4]}]
# set_property PACKAGE_PIN U15 [get_ports {led[5]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {led[5]}]
# set_property PACKAGE_PIN U14 [get_ports {led[6]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {led[6]}]
# set_property PACKAGE_PIN V14 [get_ports {led[7]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {led[7]}]

# Data input pins (PMOD JA)
set_property PACKAGE_PIN J1 [get_ports {data_in}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_in}]
# set_property PACKAGE_PIN L2 [get_ports {data_in[1]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {data_in[1]}]
# set_property PACKAGE_PIN J2 [get_ports {data_in[2]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {data_in[2]}]
# set_property PACKAGE_PIN G2 [get_ports {data_in[3]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {data_in[3]}]

set_property CONFIG_VOLTAGE 3.3 [current_design]
set_property CFGBVS VCCO [current_design]